name: terminal.prod
services:
  client:
    image: ghcr.io/koptoel/terminal/client:latest
    ports:
      - 60005:5173

  server:
    image: ghcr.io/koptoel/terminal/server:latest
    ports:
      - 60004:5006
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  backup:
    image: ghcr.io/koptoel/terminal/backup:latest
