<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.12" />    
        <PackageReference Include="Serilog" Version="4.2.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
        <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Terminal.Backend.Application\Terminal.Backend.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="DAL\Migrations\20240311185233_DitchValueGeneratorOverIdentitySequence.cs" />
      <Compile Remove="DAL\Migrations\20240311185233_DitchValueGeneratorOverIdentitySequence.Designer.cs" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DAL\Migrations\" />
    </ItemGroup>
</Project>
