- name: Deploy
  hosts: all
  gather_facts: yes

  tasks:
    - name: Log into GitHub Container Registry
      shell: "echo {{ registry_token }} | docker login ghcr.io -u {{ github_user }} --password-stdin"
      no_log: true 

    - name: Docker compose up
      shell: |
        docker compose -f {{ compose_image }} pull
        yes | docker compose --ansi never -f {{ compose_image }} up -d --remove-orphans
      environment:
        ASPNETCORE_ENVIRONMENT: "Production"
        ASPNETCORE_URLS: "http://*:5006"
        Jwt__SecretKey: "{{ jwt_secret }}"
        Jwt__Issuer: "{{ jwt_issuer | default('TerminalServer') }}"
        Jwt__Audience: "{{ jwt_audience | default('TerminalClient') }}"
        Jwt__AccessTokenExpirationMinutes: "60"
        Jwt__RefreshTokenExpirationDays: "7"
        
        Administrator__Email: "{{ admin_email }}"
        Administrator__Password: "{{ admin_password }}"
        POSTGRES_DB: "terminal"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_pass }}"
        Postgres__ConnectionString: "Host=database;Database=terminal;Username={{ postgres_user }};Password={{ postgres_pass }};Include Error Detail=true"
        
        OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
        OTEL_EXPORTER_OTLP_ENDPOINT: "{{ otel_endpoint | default('http://172.20.3.153:4318') }}"
        OTEL_EXPORTER_OTLP_HEADERS: "authorization={{ otel_headers }}"
        OTEL_RESOURCE_ATTRIBUTES: "{{ otel_attributes }}"
        OTEL_SERVICE_NAME: "terminal-backend"
        
        COMPOSE_INTERACTIVE_NO_CLI: "1"
        COMPOSE_MENU: "0"

      args:
        executable: /bin/bash
      register: compose_up
      ignore_errors: yes

    - name: Show logs on failure
      shell: "docker logs terminal.server --tail 100"
      when: compose_up is failed or (compose_up.rc is defined and compose_up.rc != 0)
      register: server_logs

    - name: Final check
      fail:
        msg: "Deployment failed! App logs: {{ server_logs.stdout | default('No logs available') }}"
      when: compose_up is failed or (compose_up.rc is defined and compose_up.rc != 0)