on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: 23

defaults:
  run:
    working-directory: ./Client

env:
  cache-name: cache-node-modules

jobs:
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Cache node module
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: Client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Format code
        run: npm run format:pipeline

      - name: Build client
        run: npm run build --if-present

      - name: Test client
        run: npm test --if-present

  test:
    needs: build-validation
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Cache node module
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: Client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint:test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server
        working-directory: .
        run: |
          docker compose --env-file .env.sample.local up --build -d --wait server database
      - name: Run Playwright tests
        run: npx playwright test --workers 2
      - name: Stop server
        if: always()
        working-directory: .
        run: docker compose -f compose.yaml -f compose.override.yaml down

  make-docs:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ build-validation, test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Cache node module
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: Client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Generate documentation
        run: npx typedoc
      - uses: actions/upload-artifact@v4
        with:
          name: typedoc
          path: Client/docs
